spring:
  config:
    import: 'aws-secretsmanager:prod/moimtogether/rds,aws-secretsmanager:prod/moimtogether/secret'
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    url: "jdbc-secretsmanager:mysql://database-1.cb0o66s8s7lt.ap-northeast-2.rds.amazonaws.com:3306/moimtogether"
    username: "${username}"
    password: "${password}"
  jpa:
    hibernate:
      ddl-auto: validate

# Email 설정 (운영용)
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${email.username}"
    password: "${email.password}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

# JWT 설정 (운영용)
jwt:
  secret: "${jwt.secret}"
  expiration: 1800000000 # 30 minutes
  refresh:
    expiration: 604800000 # 7 days

# API 키 (운영용)
api:
  authKey: "${api.authkey}"
