server:
  port: 8081

spring:
  profiles: prod2
  config:
    import: 'aws-secretsmanager:prod/moimtogether/rds,aws-secretsmanager:prod/moimtogether/secret'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://${host}:${port}/${dbname}'
    username: "${username}"
    password: "${password}"
  jpa:
    hibernate:
      ddl-auto: update

# Email 설정 (운영용)
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${email.username}"
    password: "${email.password}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

# JWT 설정 (운영용)
jwt:
  secret: "${jwt.secret}"
  expiration: 1800000000 # 30 minutes
  refresh:
    expiration: 604800000 # 7 days

# API 키 (운영용)
api:
  authKey: "${api.authkey}"
